### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by VSEphpbb** [phpbb-extensions/autogroups#12]
This is just a basic to-do list for Auto Groups:

Need to complete for Beta release:
- [x] ACP Interface PR #31 
- [ ] ACP Option to exempt groups from having their default status changed
- [x] Notifications PR #14 
- [x] Membership Days type class (called via daily cron, using `user_regdate`) PR #18 & #19 
- [ ] User Age type class ?? (called via daily cron, using `user_birthday`)
- [x] Warnings type class (called by events, using `user_warnings`) PR #25 
  - warnings added events: `core.mcp_warn_post_after`, `core.mcp_warn_user_after`
  - warnings deleted in `acp_users.php` (no event exists) and `tidy_users()` (no event exists)
- [ ] Break services.yml up (move cron, notification and type services into separate service files) PR #33 

Can be completed after Beta release:
- [ ] Inactive User type class ?? (called via daily cron, using `user_lastvisit` and `user_inactive_time`)
- [ ] Unit test the manager and controller classes
- [ ] Functional tests ?

**Comment by VSEphpbb** [comment]
Moved the items still to do in this list into individual issues to track more easily and/or assign to people.
